### ISSUE TITLE
Apply addons as last step

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubeone#1118]
**What feature would you like to be added?**

The apply step should be placed as last step in the cluster provisioning. Currently Machine Controller deployment is after it, what can cause conflicts e.g if you want to apply machinedeployment manifest via addons.
But anyway it make more sense to apply manifests after the node provisioning is started.

```
INFO[18:39:19 CEST] Applying addons…                             
WARN[18:39:29 CEST] Task failed, error was: failed to apply addons: failed to apply addons: + export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin:/usr/local/bin:/opt/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin:/usr/local/bin:/opt/bin
+ sudo KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f ./kubeone/addons/ --prune -l kubeone.io/addon
error: unable to recognize "kubeone/addons/addons.yaml": no matches for kind "MachineDeployment" in version "cluster.k8s.io/v1alpha1"
: Process exited with status 1 
WARN[18:39:34 CEST] Retrying task…   
```
**What are use cases of the feature?**
usability

**Comment by xmudrii** [comment]
The addons are intentionally applied right after running `kubeadm`, so users can deploy components such as custom CNI, cloud controller manager, CSI drivers, and similar.

**Comment by toschneck** [comment]
yeah I know, but does it harm, to deploy first the machine controller? 
This would make the management of the cluster more easy, because you can follow the changes by "infra as code"?

**Comment by kron4eg** [comment]
Here’s the problem with MachineDeployments as addons, if we talk about something like AWS, we need a lot of info from the terraform, different AWS objects IDs (vpc/subnet/etc). Theoretically we can provide this to the addon as a template variables (because addons are being rendered as templates). But then, in AWS itself we have different MD object for different subnet so which subnet should we pass down to the MachineDeployment addon as template variable? That logic is definitely outside of the kubeone competence.

On the other hand, you can have all the necessary info inside the terraform, which will be translated to the machineDeployment objects: https://docs.kubermatic.com/kubeone/v1.0/infrastructure/terraform_integration/#kubeone_workers-reference

Second possibility is simply threat machineDeployments as regular workloads manifests (as your deployments), create a helm chart or even have a static file that will be `kubectl apply -f`-ed after git merges.

In conclustion:
Please don't use addons for managing machineDeployments. Addons were never meant for this and thus will be super ugly in this use-case.

**Comment by toschneck** [comment]
@kron4eg / @xmudrii ok can see your point. If you look over the docs https://docs.kubermatic.com/kubeone/v1.0/workers/machine_controller/ it seams that is hard to manage machine workers as manifests (is may confused by created object and tf-ouput rendered workers). So may it would make sense, to describe there as well you could manage worker nodes by "plain machine deployment yaml"
