### ISSUE TITLE
Manage kubespray clusters with KubeOne

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubeone#1169]
As a user, I want to manage my existing kubespray clusters with KubeOne so that I can leverage on my KubeOne knowledge and migrate to my preferred tool. 

Acceptance Criteria
* process is started with one easy command
* no additional user input required to attain the goal
* Status prompt after succesful action

**Comment by enote-kane** [comment]
Is this actually implemented since it says "closed as **completed**"?

I wasn't able to find anything in the documentation that goes into the topic of analyzing existing cluster setups.

**Comment by kron4eg** [comment]
@enote-kane no, we dropped that idea.

**Comment by enote-kane** [comment]
@kron4eg Thx for the update, that's very unfortunate, since I have a couple of clusters not really handed over to me properly, automation not really complete, so I was looking for a tool that could potentially analyze our current setups and generate a configuration which I then could use as a base.

But I guess that's too complex for being an actual supported feature, considering all the nasty details of all the cloud providers, or?

**Comment by kron4eg** [comment]
Yeah, we've been considering it before making actual research on feasibility. In the end we had to back off on that idea :shrug:

**Comment by enote-kane** [comment]
@kron4eg Understood. Thx for the insight.
