### ISSUE TITLE
Terraform provider for KubeOne

### ISSUE THREAD

**Issue by bokysan** [kubermatic/kubeone#1342]
**What feature would you like to be added?**

Hello, I would like to propose that kubeone is is available as [terraform provider](https://www.terraform.io/docs/providers/index.html) as well.

**What are use cases of the feature?**

Currently running KubeOne after terraform includes a lot of monkey-patching and trickery with either `provisioner "local-exec"` and/or running things through external `.sh` scripts.

As KubeOne is already tied into terraform, it would make a lot sense to create a Terraform provider as well, so that a user could do something like:

```hcl
resource "kubeone_cluster" "example" {
   ...
}
```

and automatically create / update the cluster based on latest changes. This would avoid confusion, problems and a lot of unnecessary glue code.

KubeOne is already well structured to support this scenario, but a lot of commands are not marked as exported (= are private) to be able to do this independently in an external package.

**Comment by kron4eg** [comment]
Just FYI: KubeOne is not tied into terraform. We are barely integrated with terraform and the integration is very thin. 

KubeOne itself has no idea about terraform besides 2 very small points:
* automatically run `terraform output -json` if `-t .` is given
* read this output, that is defined by us.

Otherwise KubeOne would perfectly well will run together with ansible for example, or outside of any provisioning tool at all.
