### ISSUE TITLE
Addons to support custom credentials

### ISSUE THREAD

**Issue by aandrushchenko** [kubermatic/kubeone#1365]
**What feature would you like to be added?**
We are looking to be able to pass arbitrary credentials to addons not limited to the list of credentials supported by cloud provider. 
**What are use cases of the feature?**
As an example we might want to pass HETZNER_DNS_TOKEN or anything else and refer to such values via templates in addon manifests.

**Comment by jzink-tss** [comment]
+1 on this request, I am currently trying to adapt your backup-addon for SSH. At the moment, I'd have to set `AWS_SECRET_ACCESS_KEY` (or something else from the supported list) as a workaround in order to pass a ssh key to the addon's yaml file, which is kind of confusing to read for people who have no knowledge of this limitation.

It would be nice to be able to refer any environment variable (wether with or without the `env:<<...>>` syntax doesn't matter). If security is a concern, maybe a list of allowed vars could be given as an cli argument to the kubeone binary?

**Comment by xmudrii** [comment]
KubeOne 1.3 addresses this ticket in the following ways:

* You can now [override addons provided by KubeOne with your addons](https://docs.kubermatic.com/kubeone/v1.3/guides/addons/#overriding-embedded-eddons)
* We support [providing parameters to addons](https://docs.kubermatic.com/kubeone/v1.3/guides/addons/#parameters). Note that currently not all addons support custom parameters

We're planning to add support for using the `env:` syntax in KubeOne 1.4 (tracked by #1498).

For now, I'm going to close this ticket in favor of #1498. If you have any other questions, please feel free to comment on an existing ticket, create a new one, or reopen this ticket.

/close
