### ISSUE TITLE
Allow customized options for CCM

### ISSUE THREAD

**Issue by Lykos153** [kubermatic/kubeone#1426]
**What feature would you like to be added?**
I would like to be able to customize the deployment of the Cloud Controller Manager. Of course, I can do it manually, but I'd like to have it version controlled inside the manifest. Alternatively, add an option not to install the CCM at all, so users can install their own.

**What are use cases of the feature?**
The Hetzner CCM has some [options](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/load_balancers.md) for the load balancers, eg. `HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP` so the services don't have to be annotated individually.

**Comment by kron4eg** [comment]
With fresh [alpha release](https://github.com/kubermatic/kubeone/releases/tag/v1.3.0-alpha.0) we've refactored addons mechanisms and moved all CCMs that previously we've been shipping as go code to YAML addons. Here's hetzner CCM for example https://github.com/kubermatic/kubeone/tree/master/addons/ccm-hetzner.
Plus, we've made it so that it's possible to override our "internal" addons (like aforementioned CCMs) with custom. In case of hetzner all you need is to place `ccm-hetzner` directory (with your YAML) in configured addons directory.

All that will be released as kubeone v1.3, but for now I invite you to play with v1.3.0-alpha.0 pre-release, it's considered as stable.

**Comment by kron4eg** [comment]
I'll add `HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP` to out ccm-hetzner manifest.
