### ISSUE TITLE
Ignore the TLS verification for containerd insecure registries

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1547]
Enabling the `insecureRegistry` option on the containerd cluster doesn't disable the TLS verification, which can cause errors when trying to pull images from the registry. We should disable the TLS verification for insecure registries by default.

**Comment by ahmedwaleedmalik** [comment]
The insecure flag doesn't actually set the configuration to ignore the SSL certificate but instead sets the registry to plain http in the config file which leads to HTTP 400 errors. 

For containerd, at the moment when `insecureRegistry` is specified, we just use `http` for plain text instead of disabling `tls`. Which is not the required behavior.

**Comment by ahmedwaleedmalik** [comment]
@kron4eg assigning this ticket to you since you are already taking care of this with https://github.com/kubermatic/kubeone/pull/1674
