### ISSUE TITLE
How to enable feature gate in kubeone manifests

### ISSUE THREAD

**Issue by gris-gris** [kubermatic/kubeone#1714]
Is there any way to define Kubernetes [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) in kubeone manifests?

For example, I need to enable [ServiceLoadBalancerClass](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) in my cluster.

If that's not possible, that will be a great improvement for feature requests.

**Comment by kinluek** [comment]
Why is no one responding to this issue?

**Comment by kron4eg** [comment]
It got lost somehow.

Usually we don't allow open-ended configuration as many times there are additional dependencies when to "just" enable whatever flag/featuregate on random components. If there are some specific needs we address them with specific APIs.

In our given case [ServiceLoadBalancerClass](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) has been stable since 1.24. No changes required :shrug: 

/close

**Comment by kinluek** [comment]
> It got lost somehow.
> 
> 
> 
> Usually we don't allow open-ended configuration as many times there are additional dependencies when to "just" enable whatever flag/featuregate on random components. If there are some specific needs we address them with specific APIs.
> 
> 
> 
> In our given case [ServiceLoadBalancerClass](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) has been stable since 1.24. No changes required :shrug: 
> 
> 
> 
> /close

Is there anyway to enable specific feature gates though? I specifically need the UserNamespacesSupport feature. If there is no native way, can you recommend any work arounds?
