### ISSUE TITLE
Minor issues in the Digital Ocean Quickstart

### ISSUE THREAD

**Issue by rhuss** [kubermatic/kubeone#356]
I played through the example from https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-digitalocean.md and it worked nicely with some mninor issues:

* When calling `terraform output -json > tf.json` to create the input for `kubeone`, the path to the private SSH Key is missing. I had to add this path manually after export from Terraform
* I found the description "It's named as `cluster-name-kubeconfig`" a bit misleading as I first took it over by copy&paste it literally before I realised after some time that 'cluster-name' should be replaced by the name of the cluster you used when calling terraform. I think it would be better to use either an example (e.g. mycluster-kubeconfig) or format cluster-name differently (e.g. in italics, maybe within <....>)). Also don't having a dash within it would also help, as the two dashes as given here have different purposes (first one is for the example, the second one in `-kubeconfig` should be taken literally)

Otherwise, everything worked smoothly. Greate Job !

**Comment by kron4eg** [comment]
hey @rhuss, thanks for kind words!

There is a `variable "ssh_private_key_file"` defined in variables.tf, and it's empty by default because we usually rely on ssh-agent for private key handling, to avoid unencrypted ssh keys.
However with keys that you don't bother to encrypt, this variable could be set to something, in `terraform.tfvars` for example, or using ENV vars (`export TF_VAR_ssh_private_key_file=/path/to/private_unencrypted_key`
