### ISSUE TITLE
Switch to Go modules

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#524]
**What feature would you like to be added?**

With Go modules being more and more stable and becoming default soon, we should consider switching to Go modules. Kubernetes has also switched to Go modules as of 1.15.

AC

* [x] Switch to Go modules
* [x] Make code generation works after switching to Go modules

Resources

https://github.com/kubernetes/kubernetes/pull/74877
[Introduction to Go modules by Jordan Liggitt](https://www.youtube.com/watch?v=OrMA16ASz2U)

**Comment by xmudrii** [comment]
@eqrx You may find this interesting as you already tried to make this work.

**Comment by kron4eg** [comment]
for generation we'd still need vendor (which we can easily get by running `go mod vendor`).

**Comment by xmudrii** [comment]
As an example implementation, you can see how [cert-manager](https://github.com/jetstack/cert-manager) switched to Go modules.

**Comment by eqrx** [comment]
I need help here since the kubernetes code generator needs to be called via a shell script, that is not included by `go mod vendor`.

Possible ways to get around that:

- Upgrade to k8s 15 since they maybe moved to modules there
- Replace the magic [generate-internal-groups.sh](https://github.com/kubernetes/code-generator/blob/master/generate-internal-groups.sh) script
