### ISSUE TITLE
Collect anonymous usage statistics

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubeone#601]
**What feature would you like to be added?**

A potential solution could be to deploy https://github.com/kubernetes-incubator/spartakus with KubeOne. This should be optional and the default is `true` but you could disable it (remove it). 

**What are use cases of the feature?**

We would like to understand more, how KubeOne is used. For this we would like to collect anonymous usage statistics

**Comment by eqrx** [comment]
I don't see anything speaking against opt-in (and some pleasant but widely visible request for that).

If we would made it opt-out I would make sure that the user definitely knows that we are installing a collector. For example by printing that to stdout on `kubectl install`. Also the flag should be included in all important config examples.

**Comment by xmudrii** [comment]
@scheeles We have discussed this issue at the planning meeting today and we have concerns.

First, Spartakus (https://github.com/kubernetes-incubator/spartakus) is not maintained anymore. The last commit was about a year ago and most files weren't changed since 2-3 years ago. It is a question would this even work and deploying something outdated may not be a good idea.

Another problem is how would users react to have something collecting telemetry. Personally, I think we wouldn't gain any benefits with this, while we would introduce confusion and we risk that users could lose trust.

Is this something we still want to push forward?
